### ISSUE TITLE
Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.

### ISSUE THREAD

**Issue by erluxman** [SAGARSURI/MyMovies#10]
After updating my API key and altering the Module's dependency a little bit, When I try to run  `flutter packages pub run build_runner build`

on the branch added_testcase 

I get the following error. 

Anything simple I have missed? 

Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../.pub-cache/git/inject.dart-4ffd3d339d8b776b2bec8d95ae6d3d168856e76c/package/inject_generator/lib/src/context.dart:106:51: Error: Method not found: 'ParsedLibraryResultImpl.tmp'.      var parsedLibrary = ParsedLibraryResultImpl.tmp(element.library);                                                  ^^^
pub finished with exit code 78

**Comment by SAGARSURI** [comment]
I hope you resolved the issue as discussed on another channel. Hence closing.
