### ISSUE TITLE
Iphone simulator screen rotation 

### ISSUE THREAD

**Issue by rafaelwt** [SAGARSURI/MyMovies#4]
When I turn the iPhone simulator, sometimes the application is closed. if I do it many times it also closes this does not happen in the android simulator 
A message appears that says :Lost connection to device ,in the terminal
What is the problem? help me please

**Comment by SAGARSURI** [comment]
I am not able to reproduce it. I am using Android Studio. Which IDE you are using?

**Comment by rafaelwt** [comment]
Thank you for answering the question,   I am using  visual studio code and  (macOS  sierra)  so

**Comment by SAGARSURI** [comment]
This is a known issue with Visual code plugin. Check the below link:
https://github.com/flutter/flutter/issues/26945
