### ISSUE TITLE
how to load more data on scroll?

### ISSUE THREAD

**Issue by amrit-citrusleaf** [SAGARSURI/MyMovies#5]
Thanks for this easy-to-follow code/article series on Flutter's BLOC pattern. After going through the code, I  realized that there's no way we can load more data on scrolling to the bottom of the list. How do you think we can achieve it? Obviously, there's going to be Listview/gridview controller to listen to the scrolling events, but how to pass the page number to the Bloc class so that it can call the API (with new page number) again using the repository/provider classes?

Many thanks in advance!

**Comment by computerzman** [comment]
Interested ...

**Comment by SAGARSURI** [comment]
@amrit-citrusleaf and @computerzman  I am working on Part 3 of this series where you will find this feature and lot more.

**Comment by Xoshbin** [comment]
Is it implemented?

**Comment by SAGARSURI** [comment]
I will update it this weekend.

**Comment by SAGARSURI** [comment]
@amrit-citrusleaf  @computerzman @Xoshbin Implemented the feature. It's part of the master branch. Here is the commit link:
https://github.com/SAGARSURI/MyMovies/commit/e5ba19ce07391624563354905f5cb060d789f546
