### ISSUE TITLE
It seems like 'http' no longer works (?)

### ISSUE THREAD

**Issue by xexi** [SAGARSURI/MyMovies#7]
In my case, only the following method worked.
final _baseUrl = "https://api.themoviedb.org/3/movie";

**Comment by SAGARSURI** [comment]
It works. But the problem is the themoviedb api is blocked by your ISP. Trying changing the network connection or use VPN. It should work. Let me know if you are facing any other issues.

**Comment by SAGARSURI** [comment]
Closing because of no response.
